### PR TITLE
#184948253 reset user password

### PR DESCRIPTION
**Pull request by Emile-SHUMBUSHO**
What does this PR do?

This PR allows users to reset password

Description of Task to be completed?

Create a UI for the task
Code the functionality
Integrate with the backend
Test the application
How should this be manually tested?

clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-fn
switch your working directory cd e-comm-team-amigos-fn
create a .env and update it with .env-example
install all dependencies by running npm install
in your terminal, run npm start
Test the endpoints:

navigate to /reset-password
Any background context you want to provide?

Node JS installed
Node server running
What are the relevant pivotal tracker stories?

Story ID: [#184948253](https://www.pivotaltracker.com/n/projects/2639401/stories/184948253)

Screenshots (if appropriate)
UI implementation
Screenshot 2023-05-02 at 13 21 38
Screenshot 2023-04-29 at 10 36 59
passing tests
Screenshot 2023-04-28 at 11 23 26

### CODE REVIEW

**Review by wilbrord2 — APPROVED** [review]

**Review by GasanaJr — APPROVED** [review]

**Review by ericndungutse — CHANGES_REQUESTED** [review]
Resolve codeclimate.

**Review by ericndungutse — APPROVED** [review]

**Review by khevin2 — CHANGES_REQUESTED** [review]
image
This is the toast I am getting when I submit.

**Comment by Emile-SHUMBUSHO** [comment]
Issue resolved @khevin2

**Review by khevin2 — APPROVED** [review]

**Review by wilbrord2 — CHANGES_REQUESTED** [review]
Screenshot (181)

can you please increase the font size of that sentence so that it can be easy to read the message

**Comment by Emile-SHUMBUSHO** [comment]
Feedback Addressed @wilbrord2

**Review by wilbrord2 — APPROVED** [review]

**Review by Habinezajanvier — APPROVED** [review]
👍

**Pull request merged**
