### PR TITLE
#185229613 Fix responsiveness and add logout functionality

### PR DESCRIPTION
**Pull request by khevin2**
#### What does this PR do?
This PR fixes the responsiveness issues on the dashboard.
#### Description of Task to be completed?
- add responsiveness so that the dashboard is navigable on smaller screen devices
- Add __`logout`__ functionality
#### How should this be manually tested?
- Clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-fn`
- Switch your working directory `cd e-comm-team-amigos-fn`
- Install all the dependencies by running `npm install`
- Then run the project by typing `npm start`
- test the endpoint `/dashboard` and `/dashboard/*` routes

#### Any background context you want to provide?
- Have Node Js installed in your local machine
- Latest web browser

#### What are the relevant pivotal tracker/Trello stories?

Story ID: [#185229613](https://www.pivotaltracker.com/story/show/185229613)

### CODE REVIEW

**Review by ericndungutse — APPROVED** [review]

**Review by Emile-SHUMBUSHO — COMMENTED** [review]
if a user clicks on one of the link from aside bar, takeoff aside bar menu because it's covering the selected section.
Screenshot 2023-05-22 at 21 33 32

**Comment by khevin2** [comment]
> if a user clicks on one of the link from aside bar, takeoff aside bar menu because it's covering the selected section. Screenshot 2023-05-22 at 21 33 32

issue fixed

**Review by Emile-SHUMBUSHO — APPROVED** [review]

**Review by Emile-SHUMBUSHO — COMMENTED** [review]
Make this user profile be dynamic.
Screenshot 2023-05-22 at 22 45 40

**Review by AbdulKhaliq59 — APPROVED** [review]
LGTM

**Review by Habinezajanvier — APPROVED** [review]
👍

**Pull request merged**
