### PR TITLE
#184948283 implement send notification

### PR DESCRIPTION
**Pull request by Emile-SHUMBUSHO**
What does this PR do?
This PR implements in app notifications

How should this be manually tested?

- [ ] clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-fn
- [ ] switch your working directory cd e-comm-team-amigos-fn
- [ ] create a .env and update it with .env-example
- [ ] install all dependencies by running npm install
- [ ] in your terminal, run npm start

Any background context you want to provide?

- [x] Node JS installed
- [x] Node server running

What are the relevant pivotal tracker stories?
Story ID: [#184948283](https://www.pivotaltracker.com/n/projects/2639401/stories/184948283)
Screenshot 2023-05-26 at 12 18 33

### CODE REVIEW

**Review by AbdulKhaliq59 — APPROVED** [review]
LGTM

**Review by GasanaJr — APPROVED** [review]

**Review by GasanaJr — APPROVED** [review]

**Review by GasanaJr — COMMENTED** [review]
There's an issue with saving notifications

**Comment by Emile-SHUMBUSHO** [comment]
> There's an issue with saving notifications

Really?, I wasn't aware of that. I'm going to check.

**Comment by Emile-SHUMBUSHO** [comment]
@GasanaJr, Sending notifications works well on my side. lemme know if I can help to double check it.
Screenshot 2023-05-29 at 16 44 35

**Review by Habinezajanvier — APPROVED** [review]

**Pull request merged**
