### PR TITLE
#184948273 A buyer should be able to update their cart

### PR DESCRIPTION
**Pull request by AbdulKhaliq59**
#### What does this PR do?
This PR is used to make functionality to update product in user's cart
#### Description of Task to be completed?
 - [x] Create page to update user's cart
 - [x] Integrate page backend API
 - [x] Test those functionality with `jest`
#### How should this be manually tested?
- `Try to add product in a cart` 
- `/Cart`
#### What are the relevant pivotal tracker/Trello stories?
Story ID: [#184948273](https://www.pivotaltracker.com/story/show/184948273)
#### Screenshots (if appropriate)
Screenshot 2023-05-22 at 22 08 47

#### Questions:

### CODE REVIEW

**Review by Mystica52 — APPROVED** [review]
LGTM

**Review by Emile-SHUMBUSHO — COMMENTED** [review]
Inform user if they enter a number of items which exceed the number of items in the stock, Otherwise you have done a great job.

**Review by Emile-SHUMBUSHO — APPROVED** [review]

**Comment by khevin2** [comment]
image
Functionality is OK but responsiveness is not good

**Review by khevin2 — COMMENTED** [review]
image
Texts are not responsive

**Review by wilbrord2 — APPROVED** [review]

**Review by khevin2 — APPROVED** [review]

**Review by Habinezajanvier — COMMENTED** [review]
Please resolve conflicts

**Review by Habinezajanvier — APPROVED** [review]
👍

**Pull request merged**
