### PR TITLE
#184948266 User Chat Space

### PR DESCRIPTION
**Pull request by GasanaJr**
#### What does this PR do?
This PR adds a user's chat space
#### Description of Task to be completed?
- Users should be able to chat publicly on the website to ask for information and other relevant data.
#### How should this be manually tested?
- clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-fn`
- switch your working directory `cd e-comm-team-amigos-fn`
- create an `.env` and update it with `.env-example`
- install all dependencies by running `npm install`
- in your terminal run `npm start`
- to access the chat, you need to login first
#### Screenshots
- Screenshot 2023-05-26 at 9 33 13 AM
- Screenshot 2023-05-26 at 9 32 54 AM
- Screenshot 2023-05-26 at 9 32 20 AM
- Screenshot 2023-05-26 at 9 47 01 AM
- Screenshot 2023-05-26 at 9 47 14 AM
#### What are the relevant pivotal tracker stories?
Story ID: [#184928266](https://www.pivotaltracker.com/story/show/184948266)

### CODE REVIEW

**Review by Emile-SHUMBUSHO — COMMENTED** [review]
There should be a different between out going and incoming message, and if it's possible reduce the size of chat UI.
Screenshot 2023-05-26 at 09 19 43

**Comment by GasanaJr** [comment]
> There should be a different between out going and incoming message, and if it's possible reduce the size of chat UI. Screenshot 2023-05-26 at 09 19 43

Yes There is a difference between those two kinds of messages! There is also a difference between incoming, outgoing and the previous chats. So when the user clicks on the chat button the message they see are past chats from the database which are also highlighted in a separate color.

**Review by AbdulKhaliq59 — APPROVED** [review]
LGTM

**Review by AbdulKhaliq59 — APPROVED** [review]
I can suggest when someone he/she is not yet logged in and try to access chatSpace
give him/her toast notification that `access denied login first` 
otherwise it LGTM

**Review by Rwibutso — APPROVED** [review]

**Review by wilbrord2 — APPROVED** [review]

**Pull request merged**
