### PR TITLE
#184948258 Seller create product

### PR DESCRIPTION
**Pull request by GasanaJr**
#### What does this PR do?
This PR makes creation of a product possible for authenticated sellers.
#### Description of Task to be completed?
- Create figma designs
- Implement the designs in react
- Integrate with the backend
- Jest testing 
#### How should this be manually tested?
- clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-fn`
- switch your working directory `cd e-comm-team-amigos-fn`
- create an `.env` and update it with `.env-example`
- install all dependencies by running `npm install`
- in your terminal run `npm run dev`
- route to endpoint `dashboard/product/create`
- While filling the form select 4 images at the same time for product pictures
#### Screenshots
- Screenshot 2023-05-09 at 1 49 58 PM
- Screenshot 2023-05-08 at 8 37 00 AM

#### What are the relevant pivotal tracker stories?
Story ID: [#184948258](https://www.pivotaltracker.com/story/show/184948258)

### CODE REVIEW

**Review by Emile-SHUMBUSHO — COMMENTED** [review]
Provide a screenshoot of your passing tests otherwise, LGTM.

**Review by Emile-SHUMBUSHO — CHANGES_REQUESTED** [review]
From your UI design fix some margin of form container and take create product title out of the form container it could improve our UI design, otherwise LGTM.

**Review by AbdulKhaliq59 — APPROVED** [review]
LGTM

**Review by wilbrord2 — APPROVED** [review]

**Review by Rwibutso — APPROVED** [review]

**Review by Emile-SHUMBUSHO — APPROVED** [review]

**Review by Habinezajanvier — APPROVED** [review]
👍

**Pull request merged**
