### PR TITLE
#184948262 View all User Accounts and Add Roles

### PR DESCRIPTION
**Pull request by ericndungutse**
#### What does this PR do?
This PR create **users page** and **roles page**

#### Description of Task to be completed?

- [x] Create users page
- [x] Create roles page 
- [x] Integrate users page
- [x] Integrate roles page
- [x] Create tests

#### How should this be manually tested?
- In your project terminal, run `git fetch origin pull/15/head:ft-view-user-accounts-and-and-roles-184948262`
- Checkout to **ft-signup-with-email-and-password-184948250** branch
- Install all the dependencies by running npm install
- create `.env` file and set `LIVE_API_URL` to server api `url`
- Then run the project by typing `npm run dev`
- Signin with **admin account**
- Navigate to routes mentioned bellow 

#### Routes to be tested:
- `dashboard/users`
- `dashboard/roles`

#### What are the relevant pivotal tracker/Trello stories?

Story ID: [184948262](https://www.pivotaltracker.com/story/show/184948262)

#### Screenshoots

**Test Coverage**
Screenshot (19)

**UI**
Users
Screenshot (20)

Roles
Screenshot (21)

### CODE REVIEW

**Comment by Emile-SHUMBUSHO** [comment]
This PR has a conflict that should be resolved

**Review by GasanaJr — DISMISSED** [review]
Resolve the conflicting files

**Review by GasanaJr — APPROVED** [review]

**Comment by Emile-SHUMBUSHO** [comment]
Resolve the conflict from this PR otherwise LTGM.

**Review by Emile-SHUMBUSHO — APPROVED** [review]

**Review by Habinezajanvier — APPROVED** [review]
👍

**Pull request merged**
